### ISSUE TITLE
Question: wildmenu for other commands

### ISSUE THREAD

**Issue by rstacruz** [majkinetor/unite-cmdmatch#4]
Great plugin! I really love this. Is it possible to get other command's wildmenu to be opened in unite? eg, I can type:

```
:e <Tab>
```

...and get a wildmenu of the files that I can open, which I'd like to browse via Unite.

**Comment by Shougo** [comment]
Unfortunatelly, it cannot.
Because, Vim does not provide the ways to get built-in completion candidates.
It is too bad.

**Comment by rstacruz** [comment]
Ah, shame. I thought I can use this to browse [vim-projectionist](https://github.com/tpope/vim-projectionist) `:Emodel` (etc) candidates!

**Comment by majkinetor** [comment]
> Because, Vim does not provide the ways to get built-in completion candidates.

While this is true, currently plugin uses workaround for this which I think works for arbitrary command if redesigned a bit.

I have to check it to know for sure (I have a lot of work to do in next weeks so you will have to be patient).

**Comment by Shougo** [comment]
> While this is true, currently plugin uses workaround for this which I think works for arbitrary command if redesigned a bit.

Yes...
